services:
  - type: web
    name: areteseek-backend
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm install --force && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 1337
