/**
 * Seed script for WebA Strapi backend
 * Usage: STRAPI_ADMIN_EMAIL=xxx STRAPI_ADMIN_PASSWORD=xxx node scripts/seed.js
 */

// eslint-disable-next-line @typescript-eslint/no-var-requires
const fetch = require('node-fetch');
const FormData = require('form-data');

const STRAPI_URL = process.env.STRAPI_URL || 'http://localhost:1337';
const ADMIN_EMAIL = process.env.STRAPI_ADMIN_EMAIL || 'admin@bmeters.com';
const ADMIN_PASSWORD = process.env.STRAPI_ADMIN_PASSWORD || 'Admin1234!';

// ─── Helpers ────────────────────────────────────────────────────────────────

async function api(path, { method = 'GET', token, body } = {}) {
  const headers = { 'Content-Type': 'application/json' };
  if (token) headers['Authorization'] = `Bearer ${token}`;
  const res = await fetch(`${STRAPI_URL}${path}`, {
    method,
    headers,
    body: body ? JSON.stringify(body) : undefined,
  });
  const json = await res.json().catch(() => null);
  return { status: res.status, data: json };
}

async function uploadImage(apiToken, imageUrl, filename) {
  console.log(`  Uploading ${filename} ...`);
  const imgRes = await fetch(imageUrl, { headers: { 'User-Agent': 'Mozilla/5.0' } });
  const buffer = await imgRes.buffer();
  const contentType = imgRes.headers.get('content-type') || 'image/jpeg';

  const form = new FormData();
  form.append('files', buffer, { filename, contentType });

  const res = await fetch(`${STRAPI_URL}/api/upload`, {
    method: 'POST',
    headers: { ...form.getHeaders(), Authorization: `Bearer ${apiToken}` },
    body: form,
  });
  const json = await res.json();
  const file = Array.isArray(json) ? json[0] : json;
  console.log(`  ✓ Uploaded ${filename}: id=${file?.id}`);
  return file;
}

// ─── Main ────────────────────────────────────────────────────────────────────

async function main() {
  console.log('\n🌱 Starting Strapi seed...\n');

  // 1. Admin login
  console.log('1. Logging in to Strapi admin...');
  const loginRes = await api('/admin/login', {
    method: 'POST',
    body: { email: ADMIN_EMAIL, password: ADMIN_PASSWORD },
  });
  if (loginRes.status !== 200) {
    console.error('Login failed:', JSON.stringify(loginRes.data));
    process.exit(1);
  }
  const adminJwt = loginRes.data.data?.token;
  console.log('  ✓ Logged in\n');

  // 2. Create full-access API Token
  console.log('2. Creating API Token...');
  const tokenRes = await api('/admin/api-tokens', {
    method: 'POST',
    token: adminJwt,
    body: { name: `Seed-${Date.now()}`, description: 'Auto-generated by seed script', type: 'full-access', lifespan: null },
  });
  if (tokenRes.status !== 201 && tokenRes.status !== 200) {
    console.error('API token creation failed:', JSON.stringify(tokenRes.data));
    process.exit(1);
  }
  const apiToken = tokenRes.data.data?.accessKey;
  const apiTokenId = tokenRes.data.data?.id;
  console.log(`  ✓ API Token created (id=${apiTokenId})\n`);

  // 3. Upload images
  console.log('3. Uploading images to Strapi Media Library...');
  const images = {};
  images.hero   = await uploadImage(apiToken, 'https://www.bmeters.com/wp-content/uploads/2021/05/B-METERS_LS_8617-scaled-aspect-ratio-860-530.jpg', 'hero-bg.jpg');
  images.water  = await uploadImage(apiToken, 'https://www.bmeters.com/wp-content/uploads/2023/07/HYDRODIGIT-M1-sopra2.png', 'product-water-meter.png');
  images.thermal= await uploadImage(apiToken, 'https://www.bmeters.com/wp-content/uploads/2022/07/hcW4-aspect-ratio-450-450-1.png', 'product-thermal-meter.png');
  images.remote = await uploadImage(apiToken, 'https://www.bmeters.com/wp-content/uploads/2021/07/rrs-03-1-aspect-ratio-450-450.jpg', 'product-remote-reading.jpg');
  images.mce    = await uploadImage(apiToken, 'https://www.bmeters.com/wp-content/uploads/2026/03/MCE2026_post_IG_espo-3-1024x1024.jpg', 'news-mce2026.jpg');
  console.log('  ✓ All images uploaded\n');

  // 4. Create/Update Homepage single type
  console.log('4. Creating Homepage entry...');
  const homepageRes = await api('/api/homepage', {
    method: 'PUT',
    token: apiToken,
    body: {
      data: {
        heroButtonText: 'Find out more',
        companyDescription: 'B METERS srl operates as an independent, specialised company on a national and international level in the water and heat metering sector, bringing a broad offer to the market with complete and integrated solutions.',
        heroImage: images.hero?.id,
      },
    },
  });
  console.log(`  ✓ Homepage: status=${homepageRes.status}`, homepageRes.status >= 400 ? JSON.stringify(homepageRes.data).slice(0, 120) : '');
  console.log();

  // 5. Create Product Categories
  console.log('5. Creating Product Categories...');
  const categories = [
    { title: 'Water Metering', slug: 'water-metering', image: images.water?.id, accentColor: '#0C4DA2', sortOrder: 1, subcategories: [{ label: 'SMART Meters' }, { label: 'Residential Meters' }, { label: 'Bulk Meters' }, { label: 'Water Meters Accessories' }] },
    { title: 'Thermal Energy Metering', slug: 'thermal-energy-metering', image: images.thermal?.id, accentColor: '#E87722', sortOrder: 2, subcategories: [{ label: 'Mechanical Meters' }, { label: 'Ultrasonic Meters' }, { label: 'Heat cost allocators / Sensors' }, { label: 'Thermal Energy Meters Accessories' }] },
    { title: 'Remote Reading Systems', slug: 'remote-reading-systems', image: images.remote?.id, accentColor: '#585858', sortOrder: 3, subcategories: [{ label: 'LoRaWan' }, { label: 'M-BUS Wireless' }, { label: 'M-BUS' }, { label: 'Pulse Output' }] },
  ];
  for (const cat of categories) {
    const r = await api('/api/product-categories', { method: 'POST', token: apiToken, body: { data: cat } });
    console.log(`  ${r.status < 400 ? '✓' : '✗'} ${cat.title}: status=${r.status}, id=${r.data?.data?.id}`, r.status >= 400 ? JSON.stringify(r.data).slice(0, 120) : '');
  }
  console.log();

  // 6. Create News Articles
  console.log('6. Creating News Articles...');
  const articles = [
    { title: '2026 General Catalogue', summary: 'Download the new 2026 General Catalogue with all the products of B METERS, solutions for water metering and thermal energy metering.', category: 'Product', publishedAt: '2026-03-17T00:00:00.000Z' },
    { title: 'BMETERS at MCE 2026 fair, from March 24th to 27th 2026', summary: 'B METERS will be at MCE 2026, the international exhibition dedicated to HVAC and plumbing, from 24 to 27 March 2026 in Milan.', category: 'Event', image: images.mce?.id, publishedAt: '2026-03-10T00:00:00.000Z' },
    { title: 'EPD certification – Environmental Product Declaration', summary: 'B METERS obtains the EPD – Environmental Product Declaration, confirming our commitment to environmental sustainability.', category: 'Company', publishedAt: '2025-12-18T00:00:00.000Z' },
  ];
  for (const article of articles) {
    const r = await api('/api/news-articles', { method: 'POST', token: apiToken, body: { data: article } });
    console.log(`  ${r.status < 400 ? '✓' : '✗'} "${article.title.slice(0, 40)}": status=${r.status}, id=${r.data?.data?.id}`, r.status >= 400 ? JSON.stringify(r.data).slice(0, 120) : '');
  }
  console.log();

  // 7. Set public read permissions
  console.log('7. Setting public API permissions...');
  const pubRolesRes = await api('/api/users-permissions/roles', { token: apiToken });
  const publicRole = pubRolesRes.data?.roles?.find(r => r.type === 'public');
  if (publicRole) {
    const permRes = await api(`/api/users-permissions/roles/${publicRole.id}`, {
      method: 'PUT',
      token: apiToken,
      body: {
        permissions: {
          'api::homepage.homepage': { controllers: { homepage: { find: { enabled: true } } } },
          'api::product-category.product-category': { controllers: { 'product-category': { find: { enabled: true }, findOne: { enabled: true } } } },
          'api::news-article.news-article': { controllers: { 'news-article': { find: { enabled: true }, findOne: { enabled: true } } } },
          'plugin::upload.content-api': { controllers: { 'content-api': { find: { enabled: true }, findOne: { enabled: true } } } },
        },
      },
    });
    console.log(`  ✓ Permissions set: status=${permRes.status}`);
  } else {
    console.log('  ⚠ Auto-set permissions failed. Go to:');
    console.log('    Strapi admin → Settings → Roles → Public');
    console.log('    Enable "find" for: Homepage, Product-categories, News-articles');
  }

  // 8. Cleanup seed token
  if (apiTokenId) {
    await api(`/admin/api-tokens/${apiTokenId}`, { method: 'DELETE', token: adminJwt });
    console.log('\n  ✓ Seed API token removed');
  }

  console.log('\n✅ Seed complete!\n');
  console.log('→ Open http://localhost:3000 to see the result');
  console.log('→ If images missing: Strapi admin → Settings → Roles → Public → enable Upload find\n');
}

main().catch(err => {
  console.error('\n❌ Seed failed:', err);
  process.exit(1);
});
